apiVersion: v1
kind: Service
metadata:
  name: hospitalapp-service
spec:
  selector:
    app: hospitalapp-label
  ports:
    - protocol: "TCP"
      port: 8096
      targetPort: 8096
  type: LoadBalancer